version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: 80
        protocol: tcp
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo
